#pragma once

static const char* res_defaultConfig_sge =
      "config: {\n"
      "    calls: {\n"
      "        loadfunc: \"OnLoad\"\n"
      "        exitfunc: \"OnExit\"\n"
      "        updatefunc: \"OnUpdate\"\n"
      "        renderfunc: \"OnRender\"\n"
      "        updateThread: {\n"
      "            enabled: 0\n"
      "            frequency: 0.0166666666666667\n"
      "        }\n"
      "    }\n"
      "    renderer: {\n"
      "        vsync: 1\n"
      "        frequency: 0\n"
      "    }\n"
      "    window: {\n"
      "        width: 1080\n"
      "        height: 720\n"
      "        title: \"Default\"\n"
      "        resizable: 0\n"
      "    }\n"
      "    resources: {\n"
      "        threaded: 0\n"
      "        threads: 2\n"
      "    }\n"
      "}\n";